services:
  frontend:
    build: .
    container_name: episim-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run dev

volumes:
  frontend_node_modules:
